events {
    worker_connections 1024;
}

http {
    # Forward http to https
    server {
        listen 80;
        server_name _;

        location / {
        return 301 https://$host$request_uri;
        }
    }

    # Forward https to fastapi
    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate /etc/nginx/ssl/vcrge-dsi-018003.cci.wisc.edu.crt;
        ssl_certificate_key /etc/nginx/ssl/vcrge-dsi-018003.cci.wisc.edu.key;
        ssl_trusted_certificate /etc/nginx/ssl/InCommon-chain.crt;
        
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://fastapi:8765;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

        }
    }
}
