entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  api:
    address: ":8765"

certificatesResolvers:
  letsencrypt:
    acme:
      email: clo36@wisc.edu
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false

log:
  level: INFO
accessLog: {}
