DROP TABLE IF EXISTS votes;

CREATE TABLE `votes` (
  `id` INTEGER PRIMARY KEY,
  `kind` VARCHAR(8) DEFAULT NULL,
  `target` VARCHAR(8) DEFAULT NULL,
  `query` text,
  'vote' VARCHAR(4) DEFAULT NULL,
  `created_at` TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);